version: '3'
services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_RPASS}
       MYSQL_DATABASE: ${DB_DB}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASS}
       MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_EMPTY}
       MYSQL_RANDOM_ROOT_PASSWORD: ${DB_RANDOM}

   wordpress:
     depends_on:
       - db
     image: wordpress:5.5
     ports:
       - "8088:80"
     restart: always
     volumes:
       - wp_html:/var/www/html
     environment:
       WORDPRESS_DB_HOST: ${WP_HOST}
       WORDPRESS_DB_USER: ${WP_USER}
       WORDPRESS_DB_PASSWORD: ${WP_PASS}
       WORDPRESS_DB_NAME: ${WP_DBNAME}
       WORDPRESS_CONFIG_EXTRA: define( 'WP_ENVIRONMENT_TYPE', 'local' );
volumes:
    db_data: {}
    wp_html: {}
