---
- name: Install docker, compose and prerequisites
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - software-properties-common
        - python3.8
        - python3-pip
        - virtualenv
        - python3-setuptools
    - name: Install docker.io
      ansible.builtin.apt:
        name: "docker.io"
        state: present
    - name: Confirm that docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Install docker-compose
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present
    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: ubuntu
        group: ubuntu

- name: Create a Docker container for Bamboo
  hosts: infra
  become: yes
  tasks:
    - name: Set docker volume
      community.docker.docker_volume:
        name: bambooVolume
        state: present

    - name: Start docker container for bamboo
      community.docker.docker_container:
        name: bamboo
        image: jrrickerson/capstone-bamboo
        state: started
        detach: true
        restart_policy: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - bambooVolume:/var/atlassian/application-data/bamboo
        groups:
          - docker
          - 115
        ports:
          - "54663:54663"
          - "8085:8085"