---
- hosts: all
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop:
        - apt-transport-https
        - python3-pip
        - virtualenv
        - python3-setuptools
    - name: Install docker.io
      ansible.builtin.apt:
        name: "docker.io"
        state: present
    - name: Confirm that docker is active
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Install docker-compose
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
    - name: Ensure docker group exists
      ansible.builtin.group:
        name: docker
        state: present
    - name: Add user ubuntu to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true
      # ansible.builtin.get_url:
        # url: "https://github.com/docker/compose/releases/download/v2.13.0/docker-compose-linux-x86_64"
        # dest: /usr/local/bin/docker-compose
        # mode: 'u+x,g+x'
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: ubuntu
        group: ubuntu
    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

